apiVersion: v1
kind: Service
metadata:
  name: etcd-operator-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: webhook
  selector:
    etcd-operator: webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-operator-webhook
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      etcd-operator: webhook
  template:
    metadata:
      labels:
        etcd-operator: webhook
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: etcd-operator
      containers:
        - name: webhook
          image: {{ .Values.webhook.image }}
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - name: webhook
              containerPort: 8443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: 8443
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- with .Values.webhook.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      # https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8#issuecomment-636888074
      securityContext:
        fsGroup: 1000
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- if .Values.webhook.affinity }}
          {{- toYaml .Values.webhook.affinity | nindent 8 }}
        {{- else }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
        {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-operator-webhook-cert
  namespace: {{ .Release.Namespace }}
data: {} # Injected by etcd-operator-webhook
