controller:
  # List of environment items to add to the controller, for example
  # - name: AWS_REGION
  #   value: eu-west-1
  env: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image: "public.ecr.aws/etcd-operator/controller:v0.4.1@sha256:d2a76815061fb8ef5509ea3273371f3b284cce9a27d43e2db7a76bde574b461c"
webhook:
  env: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image: "public.ecr.aws/etcd-operator/webhook:v0.4.1@sha256:fbdb0ff053859662c9e5ebffe1333e45259e20c7eb7a36e6a3b2e7b62ea9de04"
